from ga4gh.testbed.report.report import Report

from compliance_suite.constants import TESTBED_DESCRIPTION, TESTBED_NAME, TESTBED_VERSION
from compliance_suite.drs_testkit import load_config_json
from compliance_suite.drs_testkit_v120 import DrsTestKitV120
from compliance_suite.drs_testkit_v130 import DrsTestKitV130
from compliance_suite.drs_testkit_v150 import DrsTestKitV150
from compliance_suite.helper import Parser
from compliance_suite.markdown_report import write_markdown_report


DRS_TESTKIT_MATRIX = {
    DrsTestKitV120.DRS_VERSION: DrsTestKitV120,
    DrsTestKitV130.DRS_VERSION: DrsTestKitV130,
    DrsTestKitV150.DRS_VERSION: DrsTestKitV150,
}


def create_report(platform_name, platform_description, server_base_url):
    report_object = Report()
    report_object.set_testbed_name(TESTBED_NAME)
    report_object.set_testbed_version(TESTBED_VERSION)
    report_object.set_testbed_description(TESTBED_DESCRIPTION)
    report_object.set_platform_name(platform_name)
    report_object.set_platform_description(platform_description)
    report_object.add_input_parameter("server_base_url", server_base_url)
    return report_object


def get_drs_testkit_class(drs_version):
    try:
        return DRS_TESTKIT_MATRIX[drs_version]
    except KeyError as e:
        supported_versions = ", ".join(sorted(DRS_TESTKIT_MATRIX.keys()))
        raise ValueError(
            f"Unsupported DRS version '{drs_version}'; "
            f"supported versions: {supported_versions}"
        ) from e


def report_runner(server_base_url, platform_name, platform_description, version, config_file):
    """
    Returns a DrsTestRunResult generated by running version-specific compliance tests.
    """
    config = load_config_json(config_file)
    report_object = create_report(platform_name, platform_description, server_base_url)

    drs_testkit_class = get_drs_testkit_class(version)
    report_object.add_input_parameter("version", version)

    drs_testkit = drs_testkit_class(server_base_url, report_object)
    return drs_testkit.run(config)


def main():
    args = Parser.parse_args()

    test_result = report_runner(
        server_base_url=args.server_base_url,
        platform_name=args.platform_name,
        platform_description=args.platform_description,
        version=args.version,
        config_file=args.config_file,
    )

    write_markdown_report(test_result.report, args.report_path)


if __name__ == "__main__":
    main()
